import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/page";
import Footer from "@/components/Footer/page";

const inter = Roboto({ subsets: ["latin"] , weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ru">
      
      <body className={inter.className}>
      <Header></Header>
      {children}
      
      <Footer></Footer>
      </body>
    </html>
  );
}
